[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.124.0"

[context.production]
    command = " hugo --gc --minify"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = " hugo --gc --minify"

[context.deploy-preview]
    command = " hugo --gc --minify"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

        [plugins.inputs]
            # If it should show more verbose logs (optional, default = true)
            debug = true
            # Relative path to source directory in case you use Hugo's "--s" option
            srcdir = "/"
